### ISSUE TITLE
Check Canticle Support on Windows...

### ISSUE THREAD

**Issue by rfliam** [Comcast/Canticle#2]

**Comment by ChrisHines** [comment]
It does not work on Windows. At minimum [`canticles.ProjectRoot`](https://github.com/Comcast/Canticle/blob/master/canticles/util.go#L285) doesn't handle Windows style file paths correctly. There are also several tests that fail:

```
C:\Users\Chris\Go\src\github.com\Comcast\Canticle>go test ./...
?       github.com/Comcast/Canticle/buildinfo   [no test files]
?       github.com/Comcast/Canticle/cant        [no test files]
--- FAIL: TestBuildInfo (0.31s)
        buildinfo_test.go:54: Error generating built file, output: # _/C_/Users/Chris/AppData/Local/Temp/cant-test324598259/buildinfo
                buildinfo\info.go:11: unknown escape sequence: C
        buildinfo_test.go:59: Error generating built file, output:
        buildinfo_test.go:61:
2015/11/09 20:31:12 INFO: Resolving repo for cdep &{SourcePath: Root:test1 Revision:test1 All:false}
2015/11/09 20:31:12 INFO: Fetching cdep &{SourcePath: Root:test1 Revision:test1 All:false}
2015/11/09 20:31:12 INFO: Resolving repo for cdep &{SourcePath: Root:test2 Revision:test2 All:false}
2015/11/09 20:31:12 INFO: Fetching cdep &{SourcePath: Root:test2 Revision:test2 All:false}
2015/11/09 20:31:12 INFO: Resolving repo for cdep &{SourcePath: Root:test3 Revision:test3 All:false}
2015/11/09 20:31:12 INFO: Resolving repo for cdep &{SourcePath: Root:test1 Revision:test1 All:false}
2015/11/09 20:31:12 INFO: Fetching cdep &{SourcePath: Root:test1 Revision:test1 All:false}
2015/11/09 20:31:12 INFO: Resolving repo for cdep &{SourcePath: Root:test2 Revision:test2 All:false}
2015/11/09 20:31:12 INFO: Fetching cdep &{SourcePath: Root:test2 Revision:test2 All:false}
2015/11/09 20:31:12 INFO: Resolving repo for cdep &{SourcePath: Root:test3 Revision:test3 All:false}
--- FAIL: TestCanticleDependencies (0.00s)
        depreader_test.go:18: Error reading valid Canticle file github.comcast.com/viper-cog/cant error: open C:\Users\Chris\Go/src/github.comcast.com\viper-cog
\cant/Canticle: The system cannot find the path specified.
        depreader_test.go:21: ReadCanticleDependencies should never return nil deps
--- FAIL: TestReadDependencies (0.09s)
        depreader_test.go:232: Error reading remotes for valid package github.comcast.com/viper-cog/cant error: cannot find package "github.comcast.com/viper-co
g/cant" in any of:
                        C:\Go\src\github.comcast.com\viper-cog\cant (from $GOROOT)
                        C:\Users\Chris\Go\src\github.comcast.com\viper-cog\cant (from $GOPATH)
        depreader_test.go:239: ReadRemoteDependencies read incorrect number of deps, got 0, expected 2
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 37 [running]:
testing.tRunner.func1(0xc0820a37a0)
        c:/go/src/testing/testing.go:450 +0x178
github.com/Comcast/Canticle/canticles.TestReadDependencies(0xc0820a37a0)
        C:/Users/Chris/Go/src/github.com/Comcast/Canticle/canticles/depreader_test.go:242 +0x1a81
testing.tRunner(0xc0820a37a0, 0xb12450)
        c:/go/src/testing/testing.go:456 +0x9f
created by testing.RunTests
        c:/go/src/testing/testing.go:561 +0x874

goroutine 1 [chan receive]:
testing.RunTests(0x9ab0c0, 0xb123c0, 0x14, 0x14, 0xc0820dc900)
        c:/go/src/testing/testing.go:562 +0x8b4
testing.(*M).Run(0xc0820abed8, 0xc0820abef8)
        c:/go/src/testing/testing.go:494 +0x77
main.main()
        github.com/Comcast/Canticle/canticles/_test/_testmain.go:92 +0x11d
FAIL    github.com/Comcast/Canticle/canticles   1.449s
```
